name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ecr-image:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com
          ECR_REGISTRY_URI: ${{ secrets.REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.REPOSITORY }}
          IMAGE_TAG: ${{ secrets.TAG }}
        run: |
          docker build -t $ECR_REGISTRY_URI/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY_URI/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY_URI/$ECR_REPOSITORY:$IMAGE_TAG"

  continuous-deployment:
    name: Pull from ECR and Deploy
    runs-on: ubuntu-latest
    needs: build-and-push-ecr-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from Amazon ECR
        id: pull-image
        env:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com
          ECR_REGISTRY_URI: ${{ secrets.REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.REPOSITORY }}
          IMAGE_TAG: ${{ secrets.TAG }}
        run: |
          docker pull $ECR_REGISTRY_URI/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Delete previous container
        id: delete-container
        run: |
          docker rm -f power || true

      - name: Serve container
        id: serving-container
        run: |
          docker run -d -p 8501:8501 --ipc="host" --name=power $ECR_REGISTRY_URI/$ECR_REPOSITORY:$IMAGE_TAG

