name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push-ecr-image:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          audience: sts.amazonaws.com
          ECR_REGISTRY_URI: ${{ secrets.ECR_REGISTRY_URI }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY_URI/$ECR_REPOSITORY:IMAGE_TAG .
          docker push $ECR_REGISTRY_URI/$ECR_REPOSITORY:IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY_URI/$ECR_REPOSITORY:IMAGE_TAG"
